# Generated by Django 3.2.8 on 2021-10-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.CharField(max_length=255)),
                ('publicacao', models.DateField()),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criador', to='app_usuario.usuario')),
            ],
            options={
                'db_table': 'jogo',
            },
        ),
    ]
